const $=s=>document.querySelector(s), M=window.MEDIA, P=window.PROJECTS, X=window.EXTRAS;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=id=>M.images.find(i=>i.id===id);
const photo=(id,cls='',eager=false)=>`<img class="${cls}" src="${img(id).src}" alt="${esc(img(id).label)}" loading="${eager?'eager':'lazy'}" decoding="async">`;
const zoom=id=>`<button type="button" data-image="${id}" aria-label="放大查看：${esc(img(id).label)}">${photo(id)}</button>`;
const video=(v,hero=false)=>`<div class="video-frame ${hero?'hero-media':''}"><video muted loop playsinline preload="${hero?'metadata':'none'}" poster="${v.poster}" data-src="${v.src}" aria-label="${esc(v.label)}" disablepictureinpicture></video><button class="play-toggle" aria-label="播放视频" type="button">▶</button>${hero?'<div class="video-label">EASYHAND / PERSONAL PROJECT</div><div class="hero-caption"><strong>五指连杆灵巧手</strong><span>16 个关节 · 6 路主动驱动 · 开源设计</span></div>':''}</div>`;
const path=location.pathname.split('/').pop();
const isAbout=path==='about.html';
$('#header').innerHTML=`<nav class="nav wrap" aria-label="主导航"><a class="brand" href="index.html"><span class="brand-mark">W.</span><span>王翊杰<small>YIJIE WANG</small></span></a><div class="nav-links"><a href="index.html#projects" ${!isAbout?'class="active"':''}>作品集</a><a href="index.html#about" ${isAbout?'class="active"':''}>关于我</a><a class="nav-cta" href="#contact">联系我 <span aria-hidden="true">↗</span></a></div></nav>`;
$('#footer').innerHTML=`<section class="contact" id="contact"><div class="wrap contact-row"><div><h2>联系我</h2><p>求职方向：机器人结构设计 · 关节模组 · 末端执行器 · 仿真分析</p><address>19108471065 · 19108471065@163.com</address></div><div class="contact-actions"><a class="button" href="mailto:19108471065@163.com">邮件联系 <span class="arrow">↗</span></a><button class="button secondary" data-wechat>微信联系</button><a class="button secondary" href="assets/resume.pdf" target="_blank" rel="noopener">查看简历 ↓</a></div></div></section><div class="wrap footer-bottom"><span>© 2026 王翊杰 · 机器人结构设计作品集</span><a href="https://github.com/wangyijie2" target="_blank" rel="noopener">GITHUB ↗</a></div>`;
const card=p=>`<a class="project-card" href="project.html?id=${p.id}"><div class="card-visual">${photo(p.cover)}<span class="card-tag">${p.tag}</span><span class="card-arrow" aria-hidden="true">↗</span></div><div class="card-info"><div><h3>${p.title}</h3><p>${p.subtitle}</p></div></div></a>`;
const gallery=ids=>`<div class="gallery">${ids.map(id=>`<figure>${zoom(id)}<figcaption>${img(id).label}</figcaption></figure>`).join('')}</div>`;
const vidGallery=vs=>`<div class="video-gallery">${vs.map(v=>`<figure>${video(v)}<figcaption>${v.label}</figcaption></figure>`).join('')}</div>`;
function home(){
 return `${about()}<div class="wrap"><section class="project-section" id="projects"><div class="section-top"><div><div class="eyebrow blue">SELECTED WORK / 01—06</div><h2>精选项目</h2></div><p>企业项目与个人实践，点击查看结构细节和演示。</p></div><div class="project-grid">${[P[1],P[0],P[2],P[3],P[4],P[5]].map(card).join('')}</div></section></div><section class="more-section"><div class="wrap"><div class="section-top"><div><div class="eyebrow blue">DESIGN EXPLORATIONS</div><h2>更多设计实践</h2></div><p>外壳、机械臂与结构仿真中的一些实践记录。</p></div><div class="extra-grid">${X.map((x,i)=>`<a class="extra-card" href="project.html?extra=${i}">${photo(x.images[0])}<div class="extra-info"><h3>${x.title}</h3><p>${x.desc}</p><span class="text-link">查看图片 →</span></div></a>`).join('')}</div></div></section>`;
}
function project(){
 const params=new URLSearchParams(location.search), id=params.get('id'),extra=params.get('extra');
 if(extra!==null){const x=X[Number(extra)];if(!x)return missing();document.title=x.title+' · 王翊杰';return `<div class="wrap"><div class="subnav"><a href="index.html#projects">← 返回作品集</a></div><section class="extra-detail"><div class="eyebrow blue">DESIGN EXPLORATIONS</div><h1>${x.title}</h1><p>${x.desc}</p>${gallery(x.images)}${Number(extra)===2?vidGallery(M.videos.filter(v=>v.project==='更多结构设计及仿真')):''}</section></div>`}
 const p=P.find(p=>p.id===id);if(!p)return missing();document.title=p.title+' · 王翊杰';
 const vs=p.videoMatch?M.videos.filter(v=>v.project.startsWith(p.videoMatch)):[];const next=P[(P.indexOf(p)+1)%P.length];
 return `<div class="wrap"><div class="subnav"><a href="index.html#projects">← 返回作品集</a> / ${p.type}</div><section class="project-heading"><div><div class="eyebrow blue">PROJECT ${p.no} / ${p.tag}</div><h1>${p.title}</h1><div class="project-meta"><div><span>个人职责</span>${p.role}</div><div><span>项目时间</span>${p.date}</div></div><div class="tags">${p.tools.map(t=>`<span>${t}</span>`).join('')}</div></div><p>${p.desc}</p></section><div class="detail-hero">${photo(p.hero,'',true)}</div><div class="metrics">${p.metrics.map(m=>`<div><strong>${m[0]}</strong><span>${m[1]}</span></div>`).join('')}</div><section class="process">${p.sections.map((s,i)=>`<article><b>0${i+1} / DESIGN NOTES</b><h3>${s[0]}</h3><p>${s[1]}</p></article>`).join('')}</section>${vs.length?`<section><div class="section-top"><div><div class="eyebrow blue">IN MOTION</div><h2>运动与实物演示</h2></div></div>${vidGallery(vs)}</section>`:''}<section><div class="section-top"><div><div class="eyebrow blue">DETAILS & PROCESS</div><h2>结构与设计记录</h2></div><p>点击图片查看细节。</p></div>${gallery(p.gallery)}</section>${p.link?`<p style="margin:0 0 45px"><a class="button" href="${p.link}" target="_blank" rel="noopener">${p.linkLabel} ↗</a></p>`:''}<a class="next-project" href="project.html?id=${next.id}"><div><span>下一个项目</span><h3>${next.title}</h3></div><span class="arrow">↗</span></a></div>`;
}
function about(){return `<div class="wrap about-main" id="about"><section class="about-intro"><div><div class="eyebrow blue">ABOUT ME</div><h1>你好，我是王翊杰。<small>机械与力学背景 · 机器人结构设计</small></h1><p class="lead">用结构设计连接想法与实物，<br>在分析、制造和调试中不断完善方案。</p><p>目前就读于长沙理工大学工程力学硕士，研究方向为结构动力学及运动控制，预计2027年6月毕业。曾赴马来西亚沙巴大学机械工程学院交换学习，具备结构力学、有限元分析、机器人机构设计与运动学方面的学习和实践经历。</p><p>在中科第五纪与北京阿米奥的实习中，参与机器人本体、外壳、末端执行器及传感器安装结构开发；独立完成双电池充电仓和折叠式腿部结构设计。个人项目覆盖五指灵巧手、四足机器人、柔性夹爪与SO-ARM101复现。</p><div class="buttons"><a class="button" href="assets/resume.pdf" target="_blank" rel="noopener">查看完整简历 ↓</a><a class="button secondary" href="#contact">与我联系 ↗</a></div></div><aside class="about-sidebar"><div class="photo-collage">${[21,17,20].map(zoom).join('')}</div><section class="sidebar-records"><div class="section-top"><div><div class="eyebrow blue">MOMENTS & MILESTONES</div><h2>学习与成长记录</h2></div><p>证书、奖项与实习生活中的一些片段。</p></div><div class="cert-grid">${[19,16,18,22,23,15].map(id=>`<figure>${zoom(id)}<figcaption>${img(id).label}</figcaption></figure>`).join('')}</div></section></aside></section><section class="about-columns"><div><h2>教育与实习经历</h2><div class="timeline-item"><span>2026.05—至今</span><h3>中科第五纪智能技术有限公司</h3><p>机器人本体研发部 · 结构工程师实习</p></div><div class="timeline-item"><span>2026.01—2026.04</span><h3>北京阿米奥机器人科技有限公司</h3><p>机器人结构工程师助理</p></div><div class="timeline-item"><span>2025.07—2025.12</span><h3>马来西亚沙巴大学 UMS</h3><p>机械工程 · 国际交换生</p></div><div class="timeline-item"><span>2024.09—2027.06（预计）</span><h3>长沙理工大学 · 工程力学硕士</h3><p>GPA 4.2 / 5 · 专业前10%</p></div><div class="timeline-item"><span>2019.09—2023.06</span><h3>长沙理工大学 · 土木工程本科</h3><p>结构力学与有限元分析基础</p></div></div><div><h2>设计与工程能力</h2><p>结构设计与制造</p><div class="capabilities">${['Creo','SolidWorks','钣金设计','二维工程图','材料与标准件选型','3D打印与装配'].map(t=>`<span>${t}</span>`).join('')}</div><p>分析与机电实践</p><div class="capabilities">${['ANSYS','Abaqus','Adams','机构运动学','ESP32','多舵机控制','URDF','遥操与示教'].map(t=>`<span>${t}</span>`).join('')}</div><h2 style="margin-top:30px">科研与荣誉</h2><p style="font-size:14px;color:var(--muted);line-height:2.1">国家发明专利1项、SCI论文1篇；多次获得学业奖学金，参与研究生科研创新项目。通过大学英语六级与计算机二级（C语言），获优秀研究生干部、英语竞赛二等奖等荣誉。</p></div></section></div>`}
function missing(){document.title='页面未找到 · 王翊杰';return `<div class="empty"><h1>暂时没有这个项目</h1><p>返回作品集，查看完整项目。</p><a class="button" href="index.html">返回作品集 →</a></div>`}
if(isAbout)location.replace('index.html#about');
$('#main').innerHTML=path==='project.html'?project():home();
const anchor=({'#portfolio':'#projects','#skills':'#about'})[location.hash]||location.hash;
if(anchor)requestAnimationFrame(()=>document.getElementById(anchor.slice(1))?.scrollIntoView());

// Files have no audio track. Muting is also enforced in the player.
const players=[...document.querySelectorAll('video')];
const sync=v=>{const b=v.parentElement.querySelector('.play-toggle');b.textContent=v.paused?'▶':'Ⅱ';b.setAttribute('aria-label',v.paused?'播放视频':'暂停视频')};
const start=v=>{v.muted=true;v.defaultMuted=true;if(!v.src)v.src=v.dataset.src;v.play().catch(()=>sync(v))};
const observer=new IntersectionObserver(entries=>{for(const e of entries){const v=e.target;v.dataset.visible=e.isIntersecting?'1':'0';if(e.isIntersecting&&!document.hidden&&v.dataset.userPaused!=='1')start(v);else v.pause()}},{threshold:.3});
players.forEach(v=>{v.muted=true;v.defaultMuted=true;v.addEventListener('volumechange',()=>{v.muted=true});v.addEventListener('play',()=>sync(v));v.addEventListener('pause',()=>sync(v));v.addEventListener('error',()=>{v.parentElement.querySelector('.play-toggle').setAttribute('aria-label','重试播放视频')});v.parentElement.querySelector('.play-toggle').addEventListener('click',()=>{if(v.paused){v.dataset.userPaused='0';start(v)}else{v.dataset.userPaused='1';v.pause()}});observer.observe(v)});
document.addEventListener('visibilitychange',()=>players.forEach(v=>{if(document.hidden)v.pause();else if(v.dataset.visible==='1'&&v.dataset.userPaused!=='1')start(v)}));
document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{const i=img(Number(b.dataset.image)),d=$('#lightbox');d.querySelector('img').src=i.src;d.querySelector('img').alt=i.label;d.querySelector('p').textContent=i.label;d.showModal()}));
document.querySelectorAll('[data-wechat]').forEach(b=>b.addEventListener('click',()=>$('#wechat').showModal()));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close-dialog').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}})});
